version: '3.8'
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_server
    ports:
      - '6379:6379'

  server:
    build: ./server
    container_name: backend_server
    ports:
      - '5000:5000'
    depends_on:
      - redis
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      REDIS_URL: redis://redis:6379
    command: npm run dev

  client:
    build: ./client
    container_name: frontend_client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - server
    command: npm run dev